server:
    port: 8800
spring:
    application:
        name: stock-service

    cloud:
        nacos:
            discovery:
                server-addr: http://localhost:8848
#                namespace: dev
                cluster-name: NJ
                metadata:
                    version: v1

my.test: fromProperties




